/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import java.awt.Desktop;
import java.awt.Dimension;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author WC-005
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private boolean casilla[][] = new boolean[3][3];
    private String turno = "usuario1";
    private int matriz[][] = new int[3][3];
    private String usuario1, usuario2;
    private int vecesGano1 = 0, vecesGano2 = 0, vecesEmpate = 0;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(String usuario1, String usuario2) {
        this.usuario1 = usuario1;
        this.usuario2 = usuario2;
        
        initComponents();
        setSize(600,600);
        setMinimumSize(new Dimension(600, 600));
        setLocationRelativeTo(null);
        llenarCasillas();
        llenarMatriz();
        
    }
    
    private void llenarCasillas(){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                casilla[i][j] = true;
            }
        }
    }
    
    private void llenarMatriz(){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                matriz[i][j] = 0;
            }
        }
    }

    private void dibujarX(JButton boton){
        boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.png")));
    }
    
    private void dibujarO(JButton boton){
        boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/o.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        botonArribaIzq = new javax.swing.JButton();
        botonArribaCentro = new javax.swing.JButton();
        botonArribaDer = new javax.swing.JButton();
        botonCentroIzq = new javax.swing.JButton();
        botonCentro = new javax.swing.JButton();
        botonCentroDer = new javax.swing.JButton();
        botonAbajoIzq = new javax.swing.JButton();
        botonAbajoCentro = new javax.swing.JButton();
        botonAbajoDer = new javax.swing.JButton();
        barraDeMenu = new javax.swing.JMenuBar();
        menuJuego = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        botonArribaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaIzqActionPerformed(evt);
            }
        });
        Panel.add(botonArribaIzq);

        botonArribaCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaCentroActionPerformed(evt);
            }
        });
        Panel.add(botonArribaCentro);

        botonArribaDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaDerActionPerformed(evt);
            }
        });
        Panel.add(botonArribaDer);

        botonCentroIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCentroIzqActionPerformed(evt);
            }
        });
        Panel.add(botonCentroIzq);

        botonCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCentroActionPerformed(evt);
            }
        });
        Panel.add(botonCentro);

        botonCentroDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCentroDerActionPerformed(evt);
            }
        });
        Panel.add(botonCentroDer);

        botonAbajoIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoIzqActionPerformed(evt);
            }
        });
        Panel.add(botonAbajoIzq);

        botonAbajoCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoCentroActionPerformed(evt);
            }
        });
        Panel.add(botonAbajoCentro);

        botonAbajoDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoDerActionPerformed(evt);
            }
        });
        Panel.add(botonAbajoDer);

        menuJuego.setText("Juego");
        menuJuego.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reset.png"))); // NOI18N
        jMenuItem1.setText("Comenzar de nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuJuego.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla.png"))); // NOI18N
        jMenuItem2.setText("Mostrar Tabla de resultados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuJuego.add(jMenuItem2);
        menuJuego.add(jSeparator1);

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuJuego.add(jMenuItem3);

        barraDeMenu.add(menuJuego);

        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        menuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAyudaMouseClicked(evt);
            }
        });
        barraDeMenu.add(menuAyuda);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void botonArribaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaIzqActionPerformed
        // TODO add your handling code here:
        if (casilla[0][0] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonArribaIzq);
                matriz[0][0] = 1;
                turno = "usuario2";
            }else{ //turno usuario 2
                dibujarO(botonArribaIzq);
                matriz[0][0] = 2;
                turno = "usuario1";
            }
            casilla[0][0] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonArribaIzqActionPerformed

    private void botonArribaCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaCentroActionPerformed
        // TODO add your handling code here:
        if (casilla[0][1] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonArribaCentro);
                matriz[0][1] = 1;
                turno = "usuario2";             
            }else{ //turno usuario 2
                dibujarO(botonArribaCentro);
                matriz[0][1] = 2;
                turno = "usuario1";
            }
            casilla[0][1] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonArribaCentroActionPerformed

    private void botonArribaDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaDerActionPerformed
        // TODO add your handling code here:
        if (casilla[0][2] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonArribaDer);
                matriz[0][2] = 1;
                turno = "usuario2";
            }else{ //turno usuario 2
                dibujarO(botonArribaDer);
                matriz[0][2] = 2;
                turno = "usuario1";
            }
            casilla[0][2] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonArribaDerActionPerformed

    private void botonCentroIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCentroIzqActionPerformed
        // TODO add your handling code here:
        if (casilla[1][0] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonCentroIzq);
                matriz[1][0] = 1;
                turno = "usuario2";
            }else{ //turno usuario 2
                dibujarO(botonCentroIzq);
                matriz[1][0] = 2;
                turno = "usuario1";
            }
            casilla[1][0] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonCentroIzqActionPerformed

    private void botonCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCentroActionPerformed
        // TODO add your handling code here:
        if (casilla[1][1] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonCentro);
                matriz[1][1] = 1;
                turno = "usuario2";
            }else{ //turno usuario 2
                dibujarO(botonCentro);
                matriz[1][1] = 2;
                turno = "usuario1";
            }
            casilla[1][1] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonCentroActionPerformed

    private void botonCentroDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCentroDerActionPerformed
        // TODO add your handling code here:
        if (casilla[1][2] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonCentroDer);
                matriz[1][2] = 1;
                turno = "usuario2";
            }else{ //turno usuario 2
                dibujarO(botonCentroDer);
                matriz[1][2] = 2;
                turno = "usuario1";
            }
            casilla[1][2] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonCentroDerActionPerformed

    private void botonAbajoIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoIzqActionPerformed
        // TODO add your handling code here:
        if (casilla[2][0] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonAbajoIzq);
                matriz[2][0] = 1;
                turno = "usuario2";
            }else{ //turno usuario 2
                dibujarO(botonAbajoIzq);
                matriz[2][0] = 2;
                turno = "usuario1";
            }
            casilla[2][0] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonAbajoIzqActionPerformed

    private void botonAbajoCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoCentroActionPerformed
        // TODO add your handling code here:
        if (casilla[2][1] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonAbajoCentro);
                matriz[2][1] = 1;
                turno = "usuario2";
            }else{ //turno usuario 2
                dibujarO(botonAbajoCentro);
                matriz[2][1] = 2;
                turno = "usuario1";
            }
            casilla[2][1] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonAbajoCentroActionPerformed

    private void botonAbajoDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoDerActionPerformed
        // TODO add your handling code here:
        if (casilla[2][2] == true) {
            if (turno.equals("usuario1")) {
                dibujarX(botonAbajoDer);
                matriz[2][2] = 1;
                turno = "usuario2";
            }else{ //turno usuario 2
                dibujarO(botonAbajoDer);
                matriz[2][2] = 2;
                turno = "usuario1";
            }
            casilla[2][2] = false;
            comprobarGanador();
        }
    }//GEN-LAST:event_botonAbajoDerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        vecesGano1 = 0; vecesGano2 = 0; vecesEmpate = 0;
        reiniciarJuego();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VentanaMostrarReseultados ventanaMR = new VentanaMostrarReseultados(this, true, usuario1, usuario2, vecesGano1, vecesGano2, vecesEmpate);
        ventanaMR.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAyudaMouseClicked
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(new URI("https://www.cope.es/actualidad/vivir/juegos-tradicionales/noticias/juegos-para-aislamiento-las-tres-raya-20200522_730488#:~:text=En%20un%20papel%20se%20hacen,sea%20vertical%2C%20horizontal%20o%20diagonal."));
        } catch (URISyntaxException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuAyudaMouseClicked

    private void comprobarGanador(){
        boolean ganador1 = false;
        boolean ganador2 = false;
        int casillasEmpate = 0;
        
        ganador1 = comprobar(1);
        ganador2 = comprobar(2);
        
        if (ganador1 == true) {
            vecesGano1++;
            VentanaGanador ventanaG = new VentanaGanador(this, true, usuario1);
            ventanaG.setVisible(true);
            reiniciarJuego();
        }else if (ganador2 == true) {
            vecesGano2++;
            VentanaGanador ventanaG = new VentanaGanador(this, true, usuario2);
            ventanaG.setVisible(true);
            reiniciarJuego();
        }else{
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    if (matriz[i][j] != 0) {
                        casillasEmpate++;
                    }
                }
            }
            if (casillasEmpate == 9) {
                vecesEmpate++;
                System.out.println("Empate");
                reiniciarJuego();
            }else{
                casillasEmpate = 0;
            }
        }
    }
    
    private boolean comprobar(int num){
        boolean ganador = false;
        
        if (matriz[0][0] == num && matriz[0][1] == num && matriz[0][2] == num) {
            ganador = true;
        }else if (matriz[1][0] == num && matriz[1][1] == num && matriz[1][2] == num) {
            ganador = true;
        }else if (matriz[2][0] == num && matriz[2][1] == num && matriz[2][2] == num) {
            ganador = true;
        }else if (matriz[0][0] == num && matriz[1][0] == num && matriz[2][0] == num) {
            ganador = true;
        }else if (matriz[0][1] == num && matriz[1][1] == num && matriz[2][1] == num) {
            ganador = true;
        }else if (matriz[0][2] == num && matriz[1][2] == num && matriz[2][2] == num) {
            ganador = true;
        }else if (matriz[0][0] == num && matriz[1][1] == num && matriz[2][2] == num) {
            ganador = true;
        }else if (matriz[0][2] == num && matriz[1][1] == num && matriz[2][0] == num) {
            ganador = true;
        }
        
        return ganador;
    } 
    
    private void reiniciarJuego(){
        llenarCasillas();
        llenarMatriz();
        
        botonAbajoCentro.setIcon(null);
        botonAbajoDer.setIcon(null);
        botonAbajoIzq.setIcon(null);
        botonCentro.setIcon(null);
        botonCentroDer.setIcon(null);
        botonCentroIzq.setIcon(null);
        botonArribaCentro.setIcon(null);
        botonArribaDer.setIcon(null);
        botonArribaIzq.setIcon(null);
   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JButton botonAbajoCentro;
    private javax.swing.JButton botonAbajoDer;
    private javax.swing.JButton botonAbajoIzq;
    private javax.swing.JButton botonArribaCentro;
    private javax.swing.JButton botonArribaDer;
    private javax.swing.JButton botonArribaIzq;
    private javax.swing.JButton botonCentro;
    private javax.swing.JButton botonCentroDer;
    private javax.swing.JButton botonCentroIzq;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuJuego;
    // End of variables declaration//GEN-END:variables
}

